"""flatten_reading

Revision ID: 7a66ef728239
Revises: e26372e1d878
Create Date: 2026-03-14 19:01:18.981257

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "7a66ef728239"
down_revision: Union[str, Sequence[str], None] = "e26372e1d878"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lecturas_riego")
    op.drop_table("lecturas_suelo")
    op.drop_table("lecturas_ambiental")
    op.add_column(
        "lecturas",
        sa.Column(
            "suelo_conductividad", sa.DECIMAL(precision=8, scale=3), nullable=True
        ),
    )
    op.add_column(
        "lecturas",
        sa.Column("suelo_temperatura", sa.DECIMAL(precision=6, scale=2), nullable=True),
    )
    op.add_column(
        "lecturas",
        sa.Column("suelo_humedad", sa.DECIMAL(precision=6, scale=2), nullable=True),
    )
    op.add_column(
        "lecturas",
        sa.Column(
            "suelo_potencial_hidrico", sa.DECIMAL(precision=8, scale=4), nullable=True
        ),
    )
    op.add_column("lecturas", sa.Column("riego_activo", sa.Boolean(), nullable=True))
    op.add_column(
        "lecturas",
        sa.Column(
            "riego_litros_acumulados", sa.DECIMAL(precision=12, scale=2), nullable=True
        ),
    )
    op.add_column(
        "lecturas",
        sa.Column(
            "riego_flujo_por_minuto", sa.DECIMAL(precision=8, scale=2), nullable=True
        ),
    )
    op.add_column(
        "lecturas",
        sa.Column(
            "ambiental_temperatura", sa.DECIMAL(precision=6, scale=2), nullable=True
        ),
    )
    op.add_column(
        "lecturas",
        sa.Column(
            "ambiental_humedad_relativa",
            sa.DECIMAL(precision=6, scale=2),
            nullable=True,
        ),
    )
    op.add_column(
        "lecturas",
        sa.Column(
            "ambiental_velocidad_viento",
            sa.DECIMAL(precision=7, scale=2),
            nullable=True,
        ),
    )
    op.add_column(
        "lecturas",
        sa.Column(
            "ambiental_radiacion_solar", sa.DECIMAL(precision=8, scale=2), nullable=True
        ),
    )
    op.add_column(
        "lecturas",
        sa.Column("ambiental_eto", sa.DECIMAL(precision=6, scale=3), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lecturas", "ambiental_eto")
    op.drop_column("lecturas", "ambiental_radiacion_solar")
    op.drop_column("lecturas", "ambiental_velocidad_viento")
    op.drop_column("lecturas", "ambiental_humedad_relativa")
    op.drop_column("lecturas", "ambiental_temperatura")
    op.drop_column("lecturas", "riego_flujo_por_minuto")
    op.drop_column("lecturas", "riego_litros_acumulados")
    op.drop_column("lecturas", "riego_activo")
    op.drop_column("lecturas", "suelo_potencial_hidrico")
    op.drop_column("lecturas", "suelo_humedad")
    op.drop_column("lecturas", "suelo_temperatura")
    op.drop_column("lecturas", "suelo_conductividad")
    op.create_table(
        "lecturas_ambiental",
        sa.Column("id", mysql.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("lectura_id", mysql.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("temperatura", mysql.DECIMAL(precision=6, scale=2), nullable=True),
        sa.Column(
            "humedad_relativa", mysql.DECIMAL(precision=6, scale=2), nullable=True
        ),
        sa.Column(
            "velocidad_viento", mysql.DECIMAL(precision=7, scale=2), nullable=True
        ),
        sa.Column(
            "radiacion_solar", mysql.DECIMAL(precision=8, scale=2), nullable=True
        ),
        sa.Column("eto", mysql.DECIMAL(precision=6, scale=3), nullable=True),
        sa.ForeignKeyConstraint(
            ["lectura_id"],
            ["lecturas.id"],
            name=op.f("lecturas_ambiental_ibfk_1"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_unicode_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("lectura_id"), "lecturas_ambiental", ["lectura_id"], unique=True
    )
    op.create_table(
        "lecturas_suelo",
        sa.Column("id", mysql.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("lectura_id", mysql.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("conductividad", mysql.DECIMAL(precision=8, scale=3), nullable=True),
        sa.Column("temperatura", mysql.DECIMAL(precision=6, scale=2), nullable=True),
        sa.Column("humedad", mysql.DECIMAL(precision=6, scale=2), nullable=True),
        sa.Column(
            "potencial_hidrico", mysql.DECIMAL(precision=8, scale=4), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["lectura_id"],
            ["lecturas.id"],
            name=op.f("lecturas_suelo_ibfk_1"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_unicode_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("lectura_id"), "lecturas_suelo", ["lectura_id"], unique=True)
    op.create_table(
        "lecturas_riego",
        sa.Column("id", mysql.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("lectura_id", mysql.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "activo", mysql.TINYINT(display_width=1), autoincrement=False, nullable=True
        ),
        sa.Column(
            "litros_acumulados", mysql.DECIMAL(precision=12, scale=2), nullable=True
        ),
        sa.Column(
            "flujo_por_minuto", mysql.DECIMAL(precision=8, scale=2), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["lectura_id"],
            ["lecturas.id"],
            name=op.f("lecturas_riego_ibfk_1"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_unicode_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("lectura_id"), "lecturas_riego", ["lectura_id"], unique=True)
    # ### end Alembic commands ###
