"""init_12_tables

Revision ID: e26372e1d878
Revises: 
Create Date: 2026-03-06 21:44:45.508824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e26372e1d878'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_cultivo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('eliminado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'cliente', name='rol_enum'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('eliminado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_index('idx_usuarios_correo', 'usuarios', ['correo'], unique=False)
    op.create_index('idx_usuarios_rol', 'usuarios', ['rol'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre_empresa', sa.String(length=200), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('eliminado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index('idx_clientes_usuario_id', 'clientes', ['usuario_id'], unique=False)
    op.create_table('tokens_refresco',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('expira_en', sa.DateTime(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('revocado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('idx_tokens_refresco_token', 'tokens_refresco', ['token'], unique=False)
    op.create_index('idx_tokens_refresco_usuario_id', 'tokens_refresco', ['usuario_id'], unique=False)
    op.create_table('predios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('ubicacion', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('eliminado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_predios_cliente_id', 'predios', ['cliente_id'], unique=False)
    op.create_table('areas_riego',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('predio_id', sa.Integer(), nullable=False),
    sa.Column('tipo_cultivo_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('tamano_area', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('eliminado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['predio_id'], ['predios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipo_cultivo_id'], ['tipos_cultivo.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_areas_riego_predio_id', 'areas_riego', ['predio_id'], unique=False)
    op.create_index('idx_areas_riego_tipo_cultivo_id', 'areas_riego', ['tipo_cultivo_id'], unique=False)
    op.create_table('ciclos_cultivo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('area_riego_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('eliminado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['area_riego_id'], ['areas_riego.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ciclos_cultivo_area_fechas', 'ciclos_cultivo', ['area_riego_id', 'fecha_fin'], unique=False)
    op.create_index('idx_ciclos_cultivo_area_id', 'ciclos_cultivo', ['area_riego_id'], unique=False)
    op.create_table('nodos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('area_riego_id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(length=128), nullable=False),
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=True),
    sa.Column('latitud', sa.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('longitud', sa.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('eliminado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['area_riego_id'], ['areas_riego.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('area_riego_id'),
    sa.UniqueConstraint('numero_serie')
    )
    op.create_index('idx_nodos_api_key', 'nodos', ['api_key'], unique=False)
    op.create_index('idx_nodos_area_riego_id', 'nodos', ['area_riego_id'], unique=False)
    op.create_table('lecturas',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nodo_id', sa.Integer(), nullable=False),
    sa.Column('marca_tiempo', sa.DateTime(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['nodo_id'], ['nodos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lecturas_nodo_tiempo', 'lecturas', ['nodo_id', 'marca_tiempo'], unique=False)
    op.create_index('idx_lecturas_tiempo', 'lecturas', ['marca_tiempo'], unique=False)
    op.create_table('lecturas_ambiental',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lectura_id', sa.BigInteger(), nullable=False),
    sa.Column('temperatura', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('humedad_relativa', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('velocidad_viento', sa.DECIMAL(precision=7, scale=2), nullable=True),
    sa.Column('radiacion_solar', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('eto', sa.DECIMAL(precision=6, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['lectura_id'], ['lecturas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lectura_id')
    )
    op.create_table('lecturas_riego',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lectura_id', sa.BigInteger(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('litros_acumulados', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('flujo_por_minuto', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['lectura_id'], ['lecturas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lectura_id')
    )
    op.create_table('lecturas_suelo',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lectura_id', sa.BigInteger(), nullable=False),
    sa.Column('conductividad', sa.DECIMAL(precision=8, scale=3), nullable=True),
    sa.Column('temperatura', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('humedad', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('potencial_hidrico', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['lectura_id'], ['lecturas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lectura_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lecturas_suelo')
    op.drop_table('lecturas_riego')
    op.drop_table('lecturas_ambiental')
    op.drop_index('idx_lecturas_tiempo', table_name='lecturas')
    op.drop_index('idx_lecturas_nodo_tiempo', table_name='lecturas')
    op.drop_table('lecturas')
    op.drop_index('idx_nodos_area_riego_id', table_name='nodos')
    op.drop_index('idx_nodos_api_key', table_name='nodos')
    op.drop_table('nodos')
    op.drop_index('idx_ciclos_cultivo_area_id', table_name='ciclos_cultivo')
    op.drop_index('idx_ciclos_cultivo_area_fechas', table_name='ciclos_cultivo')
    op.drop_table('ciclos_cultivo')
    op.drop_index('idx_areas_riego_tipo_cultivo_id', table_name='areas_riego')
    op.drop_index('idx_areas_riego_predio_id', table_name='areas_riego')
    op.drop_table('areas_riego')
    op.drop_index('idx_predios_cliente_id', table_name='predios')
    op.drop_table('predios')
    op.drop_index('idx_tokens_refresco_usuario_id', table_name='tokens_refresco')
    op.drop_index('idx_tokens_refresco_token', table_name='tokens_refresco')
    op.drop_table('tokens_refresco')
    op.drop_index('idx_clientes_usuario_id', table_name='clientes')
    op.drop_table('clientes')
    op.drop_index('idx_usuarios_rol', table_name='usuarios')
    op.drop_index('idx_usuarios_correo', table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('tipos_cultivo')
    # ### end Alembic commands ###
